"use client";

import { LoaderCircle, Lock, RotateCcw, Send } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import type { Room, RoomPlayer } from "@/features/rooms/types";
import { gameByKey } from "./registry";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import { PongBoard } from "./pong-board";

const quiz={question:"Which planet has the shortest day?",options:["Mercury","Jupiter","Mars","Neptune"],answer:1};
const emoji={question:"🌧️ + 🐈 + 🐕",options:["Animal House","Cloudy Day","Raining cats and dogs","Pet Weather"],answer:2};
const colors=["#ff9eaa","#77dce7","#f4dc69","#8de2bd"];

export function GameBoard({room,players,userId,onlineIds}:{room:Room;players:RoomPlayer[];userId:string;onlineIds:string[]}){
 const me=players.find(p=>p.player_id===userId); const state=room.public_state||{}; const game=gameByKey[room.game_type]; const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [guess,setGuess]=useState("");
 async function act(action:string,value?:string){if(busy)return;const supabase=getSupabaseBrowserClient();if(!supabase)return;setBusy(true);setError("");const {error}=await supabase.rpc("play_room_action",{p_room:room.id,p_action:action,p_value:value??null});if(error)setError(error.message);setBusy(false)}
 const scores=state.scores||{}; const winningSeats=useMemo(()=>deriveWinners(room,players),[room,players]);
 if(room.status==="completed")return <Result room={room} players={players} me={me} winningSeats={winningSeats}/>;
 return <div className="mx-auto w-full max-w-4xl"><div className="mb-4 flex gap-2 overflow-x-auto pb-2">{players.map(player=><div key={player.id} className={`min-w-35 rounded-2xl border-2 border-slate-950 p-3 ${state.turn===player.seat?"shadow-[4px_4px_0_#171821]":""}`} style={{backgroundColor:colors[player.seat-1]}}><div className="flex items-center gap-2"><span className={`h-2.5 w-2.5 rounded-full ${onlineIds.includes(player.player_id)?"bg-emerald-600":"bg-slate-400"}`}/><strong className="truncate text-xs">{player.profile?.display_name||`Player ${player.seat}`}{player.player_id===userId?" (you)":""}</strong></div><p className="mt-2 text-xl font-black">{room.game_type==="dice_dash"?`${state.positions?.[player.seat]||0}/20`:room.game_type==="basketball"?`${scores[player.seat]||0} pts`:state.scores?`${scores[player.seat]||0} pts`:`P${player.seat}`}</p></div>)}</div>
 <section className="paper-card overflow-hidden"><header className="flex items-center justify-between border-b-2 border-slate-950 px-5 py-4" style={{backgroundColor:game.color}}><div className="flex items-center gap-3"><span className="text-3xl">{game.icon}</span><div><p className="text-[10px] font-black uppercase tracking-widest opacity-60">{game.name}</p><h2 className="font-black">{state.message||"Game on!"}</h2></div></div>{busy&&<LoaderCircle className="animate-spin" size={20}/>}</header>
 <div className="min-h-[430px] p-5 sm:p-8">
 {room.game_type==="basketball"&&<Basketball state={state} mySeat={me?.seat} busy={busy} shoot={()=>act("shoot")}/>} 
 {room.game_type==="rps"&&<RPS state={state} mySeat={me?.seat} choose={v=>act("choose",v)} busy={busy}/>} 
 {room.game_type==="number_guess"&&<NumberGuess state={state} guess={guess} setGuess={setGuess} submit={(e)=>{e.preventDefault();act("guess",guess).then(()=>setGuess(""))}} busy={busy}/>} 
 {room.game_type==="tic_tac_toe"&&<TicTacToe state={state} mySeat={me?.seat} place={i=>act("place",String(i))} busy={busy}/>} 
 {room.game_type==="dice_dash"&&<DiceDash state={state} players={players} mySeat={me?.seat} roll={()=>act("roll")} busy={busy}/>} 
 {room.game_type==="quick_quiz"&&<QuestionCard data={quiz} state={state} answer={i=>act("answer",String(i))} mySeat={me?.seat} busy={busy}/>} 
 {room.game_type==="emoji_decode"&&<QuestionCard data={emoji} state={state} answer={i=>act("answer",String(i))} mySeat={me?.seat} busy={busy} emoji/>} 
 {room.game_type==="ping_pong"&&me&&<PongBoard room={room} players={players} me={me}/>} 
 </div>{error&&<p role="alert" className="border-t-2 border-red-200 bg-red-50 px-5 py-3 text-sm font-bold text-red-700">{error}</p>}</section></div>
}

function Basketball({state,mySeat,busy,shoot}:{state:Room["public_state"];mySeat?:number;busy:boolean;shoot:()=>void}){const mine=state.turn===mySeat;return <div className="text-center"><div className="relative mx-auto h-64 max-w-xl overflow-hidden rounded-[28px] border-2 border-slate-950 bg-[#de945c]"><div className="absolute inset-x-0 top-0 h-28 bg-[#8ddcf0]"/><div className="absolute left-1/2 top-12 h-24 w-3 -translate-x-1/2 bg-slate-700"/><div className="absolute left-1/2 top-20 h-3 w-28 -translate-x-1/2 border-2 border-red-700 bg-white"/><div className="absolute left-1/2 top-24 h-12 w-20 -translate-x-1/2 rounded-b-full border-x-4 border-b-4 border-red-600"/><span className={`absolute bottom-7 left-1/2 -translate-x-1/2 text-6xl transition ${busy?"-translate-y-36 scale-75 rotate-180":""}`}>🏀</span><div className="absolute inset-x-0 bottom-0 h-3 bg-[#80502e]"/></div><p className="mt-5 text-sm font-bold">Shot {Math.min(5,(state.shots?.[String(mySeat)]||0)+1)} of 5</p><button onClick={shoot} disabled={!mine||busy} className="arcade-button mt-4 bg-[#ffb563] px-8 py-4 shadow-[4px_4px_0_#171821]">{mine?"HOLD & SHOOT":"WATCH THEIR SHOT"}</button></div>}
function RPS({state,mySeat,choose,busy}:{state:Room["public_state"];mySeat?:number;choose:(v:string)=>void;busy:boolean}){const locked=Boolean(mySeat&&state.choices?.[mySeat]);return <div className="text-center"><div className="mx-auto grid max-w-2xl grid-cols-3 gap-3">{[["rock","✊","ROCK"],["paper","📄","PAPER"],["scissors","✂️","SCISSORS"]].map(([value,icon,label])=><button key={value} disabled={locked||busy} onClick={()=>choose(value)} className="group cursor-pointer rounded-[24px] border-2 border-slate-950 bg-[#f0edff] p-4 shadow-[3px_3px_0_#171821] transition hover:-translate-y-2 disabled:cursor-not-allowed disabled:opacity-40"><span className="block text-5xl sm:text-7xl group-hover:scale-110">{icon}</span><strong className="mt-3 block text-xs">{label}</strong></button>)}</div>{locked&&<div className="mx-auto mt-7 inline-flex items-center gap-2 rounded-full border-2 border-slate-950 bg-[#f4dc69] px-5 py-2 text-sm font-black"><Lock size={15}/> Choice sealed. Waiting…</div>}</div>}
function NumberGuess({state,guess,setGuess,submit,busy}:{state:Room["public_state"];guess:string;setGuess:(s:string)=>void;submit:(e:FormEvent)=>void;busy:boolean}){const trail=(state.guesses||[]).slice(-6).reverse();return <div><div className="mx-auto max-w-md text-center"><p className="text-8xl font-black tracking-[-.08em] text-[#9fcaff]">1—100</p><form onSubmit={submit} className="mt-7 flex gap-2"><input value={guess} onChange={e=>setGuess(e.target.value)} min={1} max={100} type="number" required placeholder="Your guess" className="min-w-0 flex-1 rounded-full border-2 border-slate-950 px-5 py-3 text-center text-xl font-black outline-none"/><button disabled={busy} className="arcade-button bg-slate-950 text-white"><Send size={17}/><span className="hidden sm:inline">GUESS</span></button></form></div><div className="mx-auto mt-8 max-w-md space-y-2">{trail.map((g,i)=><div key={`${g.seat}-${g.value}-${i}`} className="flex justify-between rounded-xl border-2 border-slate-950 bg-white px-4 py-2 text-sm"><strong>Player {g.seat}: {g.value}</strong><span>{g.hint==="Too low"?"⬆️":g.hint==="Too high"?"⬇️":"🎯"} {g.hint}</span></div>)}</div></div>}
function TicTacToe({state,mySeat,place,busy}:{state:Room["public_state"];mySeat?:number;place:(i:number)=>void;busy:boolean}){return <div className="mx-auto grid max-w-sm grid-cols-3 gap-2">{(state.board||Array(9).fill("")).map((cell,i)=><button key={i} onClick={()=>place(i)} disabled={Boolean(cell)||state.turn!==mySeat||busy} className="aspect-square cursor-pointer rounded-2xl border-2 border-slate-950 bg-[#fff8dd] text-5xl font-black shadow-[3px_3px_0_#171821] disabled:cursor-not-allowed">{cell}</button>)}</div>}
function DiceDash({state,players,mySeat,roll,busy}:{state:Room["public_state"];players:RoomPlayer[];mySeat?:number;roll:()=>void;busy:boolean}){return <div><div className="grid grid-cols-5 gap-2">{Array.from({length:20},(_,i)=>i+1).map(square=><div key={square} className="relative aspect-square rounded-xl border-2 border-slate-950 bg-[#fff8dd] p-1 text-xs font-black"><span className="opacity-40">{square}</span><div className="absolute inset-0 flex flex-wrap items-center justify-center">{players.filter(p=>(state.positions?.[p.seat]||0)===square).map(p=><span key={p.id} className="h-5 w-5 rounded-full border-2 border-slate-950" style={{backgroundColor:colors[p.seat-1]}}/>)}</div></div>)}</div><div className="mt-7 text-center"><button onClick={roll} disabled={state.turn!==mySeat||busy} className="arcade-button bg-[#f4dc69] px-8 py-4 shadow-[4px_4px_0_#171821]"><span className="text-2xl">🎲</span>{state.turn===mySeat?"ROLL THE DICE":"WAITING…"}</button></div></div>}
function QuestionCard({data,state,answer,mySeat,busy,emoji=false}:{data:{question:string;options:string[];answer:number};state:Room["public_state"];answer:(i:number)=>void;mySeat?:number;busy:boolean;emoji?:boolean}){const locked=Boolean(mySeat!==undefined&&state.answers?.[mySeat]!==undefined);return <div className="mx-auto max-w-2xl text-center"><p className={emoji?"text-6xl sm:text-8xl":"text-2xl font-black sm:text-4xl"}>{data.question}</p><p className="mt-3 text-xs font-black uppercase tracking-widest text-slate-400">Pick once. No take-backs.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{data.options.map((option,i)=><button key={option} onClick={()=>answer(i)} disabled={locked||busy} className="cursor-pointer rounded-2xl border-2 border-slate-950 bg-white p-4 text-left font-black shadow-[3px_3px_0_#171821] transition hover:-translate-y-1 disabled:cursor-not-allowed disabled:opacity-50"><span className="mr-3 opacity-35">{String.fromCharCode(65+i)}</span>{option}</button>)}</div>{locked&&<p className="mt-6 font-black text-[#7357ff]">ANSWER LOCKED ✓</p>}</div>}
function deriveWinners(room:Room,players:RoomPlayer[]){const state=room.public_state;if(typeof state.winnerSeat==="number")return [state.winnerSeat];if(["basketball","quick_quiz","emoji_decode"].includes(room.game_type)){const values=players.map(p=>Number(state.scores?.[p.seat]||0));const top=Math.max(...values);const seats=players.filter((_,i)=>values[i]===top).map(p=>p.seat);return seats.length===players.length?[]:seats}if(room.game_type==="rps"){const choices=state.choices||{};const unique=[...new Set(Object.values(choices))];if(unique.length!==2)return [];const winning=unique.includes("rock")&&unique.includes("scissors")?"rock":unique.includes("scissors")&&unique.includes("paper")?"scissors":"paper";return players.filter(p=>choices[p.seat]===winning).map(p=>p.seat)}return []}
function Result({room,players,me,winningSeats}:{room:Room;players:RoomPlayer[];me?:RoomPlayer;winningSeats:number[]}){const supabase=getSupabaseBrowserClient();const [busy,setBusy]=useState(false);const winners=players.filter(p=>winningSeats.includes(p.seat));const draw=winningSeats.length===0||winningSeats.length===players.length;const outcome=draw?"IT’S A DRAW!":winningSeats.includes(me?.seat||0)?"YOU WIN!":"GOOD GAME!";const summary=draw?"Nobody walks away undefeated.":`${winners.map(w=>w.profile?.display_name||`Player ${w.seat}`).join(" & ")} ${winners.length>1?"take":"takes"} the round.`;async function rematch(){setBusy(true);await supabase?.rpc("rematch_room",{p_room:room.id});setBusy(false)}return <section className="paper-card mx-auto max-w-2xl overflow-hidden text-center"><div className="checker border-b-2 border-slate-950 px-5 py-12"><span className="text-7xl">🏆</span><p className="eyebrow mt-5">Game over</p><h1 className="mt-2 text-5xl font-black tracking-[-.06em]">{outcome}</h1><p className="mt-3 text-slate-600">{summary}</p></div><div className="p-6"><div className="mb-6 flex justify-center gap-3">{players.map(p=><div key={p.id} className={`rounded-xl border-2 border-slate-950 px-3 py-2 text-xs font-black ${winningSeats.includes(p.seat)?"shadow-[3px_3px_0_#171821]":"opacity-60"}`} style={{backgroundColor:colors[p.seat-1]}}>{p.profile?.display_name||`P${p.seat}`}</div>)}</div>{room.host_id===me?.player_id?<button onClick={rematch} disabled={busy} className="arcade-button bg-[#f4dc69] shadow-[4px_4px_0_#171821]"><RotateCcw size={17}/> REMATCH</button>:<p className="text-sm font-bold text-slate-500">Waiting for the host to call a rematch…</p>}<a href="/dashboard" className="mx-auto mt-5 block text-xs font-black underline decoration-2 underline-offset-4">BACK TO THE ARCADE</a></div></section>}
