"use client";

import type { RealtimeChannel } from "@supabase/supabase-js";
import { useCallback, useEffect, useRef, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import type { Room, RoomPlayer } from "@/features/rooms/types";

type Frame={x:number;y:number;vx:number;vy:number;left:number;right:number};
const initial=():Frame=>({x:400,y:210,vx:5*(Math.random()>.5?1:-1),vy:3,left:170,right:170});
export function PongBoard({room,players,me}:{room:Room;players:RoomPlayer[];me:RoomPlayer}){
 const canvas=useRef<HTMLCanvasElement|null>(null);const frame=useRef<Frame>(initial());const channel=useRef<RealtimeChannel|null>(null);const raf=useRef(0);const lastSend=useRef(0);const [status,setStatus]=useState("CONNECTING");const [pressed,setPressed]=useState({up:false,down:false});const host=room.host_id===me.player_id;const supabase=getSupabaseBrowserClient();
 const point=useCallback(async(seat:number)=>{await supabase?.rpc("play_room_action",{p_room:room.id,p_action:"point",p_value:String(seat)});frame.current=initial()},[room.id,supabase]);
 useEffect(()=>{if(!supabase)return;const ch=supabase.channel(`pong:${room.id}`,{config:{broadcast:{self:false,ack:false}}});channel.current=ch;ch.on("broadcast",{event:"frame"},({payload})=>{if(!host)frame.current=payload as Frame}).on("broadcast",{event:"paddle"},({payload})=>{if(host)frame.current.right=Math.max(0,Math.min(340,Number(payload.y))) }).subscribe(s=>setStatus(s==="SUBSCRIBED"?"LIVE":"CONNECTING"));return()=>{supabase.removeChannel(ch);channel.current=null}},[host,room.id,supabase]);
 useEffect(()=>{function key(e:KeyboardEvent,on:boolean){if(["ArrowUp","ArrowDown","w","s"].includes(e.key))e.preventDefault();if(e.key==="ArrowUp"||e.key==="w")setPressed(p=>({...p,up:on}));if(e.key==="ArrowDown"||e.key==="s")setPressed(p=>({...p,down:on}))}const kd=(e:KeyboardEvent)=>key(e,true),ku=(e:KeyboardEvent)=>key(e,false);window.addEventListener("keydown",kd);window.addEventListener("keyup",ku);return()=>{window.removeEventListener("keydown",kd);window.removeEventListener("keyup",ku)}},[]);
 useEffect(()=>{const ctx=canvas.current?.getContext("2d");if(!ctx)return;let active=true;function loop(time:number){if(!active||!ctx)return;const f=frame.current;const ownKey=host?"left":"right";if(pressed.up)f[ownKey]=Math.max(0,f[ownKey]-7);if(pressed.down)f[ownKey]=Math.min(340,f[ownKey]+7);if(!host&&channel.current&&time-lastSend.current>40){channel.current.send({type:"broadcast",event:"paddle",payload:{y:f.right}});lastSend.current=time}
 if(host){f.x+=f.vx;f.y+=f.vy;if(f.y<8||f.y>412){f.vy*=-1;f.y=Math.max(8,Math.min(412,f.y))}if(f.x<35&&f.x>18&&f.y>f.left&&f.y<f.left+80){f.vx=Math.abs(f.vx)*1.03;f.vy+=(f.y-(f.left+40))*.035}if(f.x>765&&f.x<782&&f.y>f.right&&f.y<f.right+80){f.vx=-Math.abs(f.vx)*1.03;f.vy+=(f.y-(f.right+40))*.035}if(f.x<0)point(2);if(f.x>800)point(1);if(channel.current&&time-lastSend.current>40){channel.current.send({type:"broadcast",event:"frame",payload:f});lastSend.current=time}}
 ctx.fillStyle="#11131b";ctx.fillRect(0,0,800,420);ctx.setLineDash([12,12]);ctx.strokeStyle="#ffffff35";ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(400,0);ctx.lineTo(400,420);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle="#ff9eaa";ctx.fillRect(20,f.left,15,80);ctx.fillStyle="#77dce7";ctx.fillRect(765,f.right,15,80);ctx.fillStyle="#f4dc69";ctx.beginPath();ctx.arc(f.x,f.y,10,0,Math.PI*2);ctx.fill();raf.current=requestAnimationFrame(loop)}raf.current=requestAnimationFrame(loop);return()=>{active=false;cancelAnimationFrame(raf.current)}},[host,point,pressed]);
 function move(dir:-1|1){const key=host?"left":"right";frame.current[key]=Math.max(0,Math.min(340,frame.current[key]+dir*34));if(!host)channel.current?.send({type:"broadcast",event:"paddle",payload:{y:frame.current.right}})}
 return <div><div className="relative overflow-hidden rounded-2xl border-2 border-slate-950 bg-slate-950"><canvas ref={canvas} width={800} height={420} className="block aspect-[800/420] w-full"/><span className={`absolute right-3 top-3 rounded-full border border-white/20 bg-black/50 px-2 py-1 text-[9px] font-black tracking-widest ${status==="LIVE"?"text-emerald-300":"text-amber-300"}`}>● {status}</span><div className="pointer-events-none absolute inset-x-0 top-4 flex justify-center gap-10 text-3xl font-black text-white"><span>{room.public_state.scores?.["1"]||0}</span><span className="opacity-30">:</span><span>{room.public_state.scores?.["2"]||0}</span></div></div><div className="mt-5 flex justify-center gap-3"><button onPointerDown={()=>move(-1)} className="arcade-button h-14 w-28 bg-white text-xl">▲</button><button onPointerDown={()=>move(1)} className="arcade-button h-14 w-28 bg-white text-xl">▼</button></div><p className="mt-3 text-center text-xs font-bold text-slate-400">Use W/S or arrow keys · First to 5</p>{players.length<2&&<p className="mt-2 text-center text-sm font-black text-amber-600">Waiting for an opponent…</p>}</div>
}
