import { CharacterArchetype, CharacterStats } from "./types";

export const CHARACTERS: Record<CharacterArchetype, CharacterStats> = {
  balanced: {
    key: "balanced",
    name: "Vanguard",
    title: "The All-Rounder",
    hp: 100,
    maxHp: 100,
    speed: 7.2,
    jumpVelocity: 9.0,
    lightDamage: 10,
    heavyDamage: 18,
    attackSpeed: 1.0,
    knockbackMult: 1.0,
    blockMitigation: 0.65, // 65% damage reduction
    specialName: "Energy Strike",
    specialCooldown: 8.0,
    specialDamage: 28,
    color: "#ff3366",
    modelIcon: "⚔️",
    description: "Balanced health, speed, and damage. A versatile fighter suited for any battle situation.",
  },
  speed: {
    key: "speed",
    name: "Stryker",
    title: "Swift Assassin",
    hp: 85,
    maxHp: 85,
    speed: 9.5,
    jumpVelocity: 10.2,
    lightDamage: 8,
    heavyDamage: 15,
    attackSpeed: 1.35,
    knockbackMult: 0.8,
    blockMitigation: 0.55,
    specialName: "Dash Strike",
    specialCooldown: 6.0,
    specialDamage: 22,
    color: "#00d2ff",
    modelIcon: "⚡",
    description: "Rapid movement and high-frequency attacks. Lower health but fast dodge recovery.",
  },
  power: {
    key: "power",
    name: "Titan",
    title: "Heavy Brawler",
    hp: 120,
    maxHp: 120,
    speed: 5.6,
    jumpVelocity: 7.8,
    lightDamage: 13,
    heavyDamage: 24,
    attackSpeed: 0.8,
    knockbackMult: 1.55,
    blockMitigation: 0.7,
    specialName: "Ground Slam",
    specialCooldown: 10.0,
    specialDamage: 35,
    color: "#ffaa00",
    modelIcon: "🥊",
    description: "Devastating raw power and high knockback. Slower movement, but hits like a truck.",
  },
  defender: {
    key: "defender",
    name: "Aegis",
    title: "Iron Guardian",
    hp: 130,
    maxHp: 130,
    speed: 6.0,
    jumpVelocity: 8.0,
    lightDamage: 9,
    heavyDamage: 16,
    attackSpeed: 0.9,
    knockbackMult: 0.95,
    blockMitigation: 0.85, // 85% block mitigation
    specialName: "Shield Burst",
    specialCooldown: 9.0,
    specialDamage: 25,
    color: "#00e676",
    modelIcon: "🛡️",
    description: "Maximum health and impenetrable blocking ability. Absorbs massive incoming damage.",
  },
};

export function getCharacterConfig(archetype?: string): CharacterStats {
  const key = (archetype as CharacterArchetype) || "balanced";
  return CHARACTERS[key] || CHARACTERS.balanced;
}
