"use client";

import { Gamepad2, Radio, Swords, Trophy, UsersRound, type LucideIcon } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ProtectedPage } from "@/components/protected-page";
import { useAuth } from "@/components/auth-provider";
import { games } from "@/features/games/registry";
import { RoomLauncher } from "@/features/rooms/room-launcher";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

type Result={id:string;game_type:string;outcome:string;score:number;top_score:number;opponent_names:string[];created_at:string};
export default function DashboardPage(){
 const {profile,user}=useAuth(); const name=profile?.display_name||user?.user_metadata?.display_name||"Player"; const [filter,setFilter]=useState<"all"|"duel"|"party">("all"); const [results,setResults]=useState<Result[]>([]); const shown=games.filter(g=>filter==="all"||(filter==="party"?g.maxPlayers>2:g.maxPlayers===2));
 const stats: {label:string;value:number;icon:LucideIcon;color:string}[]=[{label:"Played",value:profile?.games_played??0,icon:Gamepad2,color:"#fff"},{label:"Wins",value:profile?.wins??0,icon:Trophy,color:"#f4dc69"},{label:"Losses",value:profile?.losses??0,icon:Swords,color:"#ffb0bb"},{label:"Draws",value:profile?.draws??0,icon:UsersRound,color:"#a7efc8"}];
 useEffect(()=>{const supabase=getSupabaseBrowserClient();if(!supabase||!user)return;supabase.from("game_results").select("*").eq("player_id",user.id).order("created_at",{ascending:false}).limit(4).then(({data})=>setResults((data||[]) as Result[]))},[user]);
 return <ProtectedPage><main className="min-h-screen bg-[#fffdf7] pb-28"><section className="border-b-2 border-slate-950 bg-[#f0edff]"><div className="mx-auto grid max-w-6xl gap-8 px-5 py-10 lg:grid-cols-[1fr_auto] lg:items-end lg:px-8 lg:py-14"><div><div className="inline-flex items-center gap-2 rounded-full border-2 border-slate-950 bg-[#a7efc8] px-3 py-1.5 text-xs font-black"><Radio size={13}/> ONLINE & READY</div><h1 className="mt-5 max-w-3xl text-[clamp(2.8rem,7vw,5.5rem)] font-black leading-[.87] tracking-[-.07em]">Pick a game.<br/><span className="text-[#7357ff]">Call a friend.</span></h1><p className="mt-5 text-slate-600">Welcome back, <strong className="text-slate-950">{name}</strong>. Your next story starts with a room code.</p></div><RoomLauncher/></div></section>
 <div className="mx-auto max-w-6xl px-5 lg:px-8"><section className="-mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{stats.map(({label,value,icon:Icon,color})=><article key={label} className="paper-card flex items-center justify-between p-4" style={{backgroundColor:color}}><div><p className="text-[10px] font-black uppercase tracking-widest opacity-55">{label}</p><p className="mt-1 text-3xl font-black">{value}</p></div><Icon size={21}/></article>)}</section>
 <section className="py-14"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">The game shelf</p><h2 className="mt-2 text-3xl font-black tracking-[-.04em]">What are we playing?</h2></div><div className="flex w-fit rounded-full border-2 border-slate-950 bg-white p-1">{(["all","duel","party"] as const).map(item=><button onClick={()=>setFilter(item)} key={item} className={`cursor-pointer rounded-full px-4 py-2 text-xs font-black capitalize ${filter===item?"bg-slate-950 text-white":""}`}>{item}</button>)}</div></div>
 <div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{shown.map((game,i)=><article key={game.key} className="group relative overflow-hidden rounded-[26px] border-2 border-slate-950 p-4 transition hover:-translate-y-2 hover:rotate-[-1deg] hover:shadow-[6px_7px_0_#171821]" style={{backgroundColor:game.color}}><div className="flex items-start justify-between"><span className="grid h-20 w-20 place-items-center rounded-2xl border-2 border-slate-950 bg-white/75 text-5xl transition group-hover:rotate-6 group-hover:scale-105">{game.icon}</span><span className="rounded-full border-2 border-slate-950 bg-white px-2.5 py-1 text-[10px] font-black uppercase">{game.tag}</span></div><h3 className="mt-5 text-xl font-black leading-tight" style={{color:game.ink}}>{game.name}</h3><p className="mt-2 min-h-15 text-sm leading-5 opacity-70">{game.description}</p><div className="mt-5 flex items-center justify-between border-t-2 border-slate-950/15 pt-3"><span className="text-xs font-black">{game.players} PLAYERS</span><span className="text-lg font-black">0{i+1}</span></div></article>)}</div></section>
 <section className="grid gap-5 pb-10 lg:grid-cols-[1.4fr_.6fr]"><article className="paper-card p-6"><div className="flex items-center justify-between"><div><p className="eyebrow">Recent scorecards</p><h2 className="mt-2 text-xl font-black">Last played</h2></div><Link href="/history" className="text-xs font-black underline decoration-2 underline-offset-4">FULL HISTORY</Link></div>{results.length?<div className="mt-5 divide-y-2 divide-slate-100">{results.map(result=>{const game=games.find(g=>g.key===result.game_type);return <div key={result.id} className="flex items-center gap-4 py-3"><span className="grid h-11 w-11 place-items-center rounded-xl border-2 border-slate-950 text-2xl" style={{backgroundColor:game?.color}}>{game?.icon||"🎮"}</span><div className="min-w-0 flex-1"><strong className="block truncate text-sm">{game?.shortName||result.game_type}</strong><span className="text-xs text-slate-500">vs {result.opponent_names.join(", ")||"the room"}</span></div><span className={`rounded-full border-2 border-slate-950 px-3 py-1 text-xs font-black ${result.outcome==="win"?"bg-[#a7efc8]":result.outcome==="draw"?"bg-[#f4dc69]":"bg-[#ffb0bb]"}`}>{result.outcome.toUpperCase()}</span></div>})}</div>:<div className="grid min-h-40 place-items-center text-center"><div><span className="text-4xl">🕹️</span><p className="mt-3 font-black">No scorecards—yet.</p><p className="mt-1 text-sm text-slate-500">Make a room and change that.</p></div></div>}</article><article className="paper-card relative overflow-hidden bg-slate-950 p-6 text-white"><div className="absolute -right-10 -top-10 text-9xl opacity-10">✦</div><p className="eyebrow text-[#a7efc8]">House rules</p><h2 className="mt-3 text-2xl font-black">Good game,<br/>better company.</h2><p className="mt-4 text-sm leading-6 text-slate-400">Room links expire after 24 hours. Invite up to three friends and keep the trash talk friendly.</p></article></section></div></main></ProtectedPage>
}
